In [17]:
import numpy as np

In [18]:
constant = 1/np.sqrt(2)

H = np.matrix([
                        [1, 1],
                        [1,-1]
])

CNOT = np.matrix([
                [1, 0, 0, 0],
                [0, 1, 0, 0],
                [0, 0, 0, 1],
                [0, 0, 1, 0]
])

NOT = np.matrix([
                [0, 1],
                [1, 0]
])

I = np.matrix([
                [1, 0],
                [0, 1]
])

In [19]:
H_NOT = np.tensordot(H, NOT, 0)
H_NOT = H_NOT.transpose((0,2,1,3)).reshape((4,4))
print(H_NOT)

[[ 0  1  0  1]
 [ 1  0  1  0]
 [ 0  1  0 -1]
 [ 1  0 -1  0]]


In [20]:
H_NOT_CNOT = H_NOT*CNOT
print(H_NOT_CNOT)

[[ 0  1  1  0]
 [ 1  0  0  1]
 [ 0  1 -1  0]
 [ 1  0  0 -1]]


In [21]:
I_NOT = np.tensordot(I, NOT, 0)
I_NOT = I_NOT.transpose((0,2,1,3)).reshape((4,4))
print(I_NOT)

[[0 1 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]]


In [22]:
res = H_NOT_CNOT*I_NOT
print(res)

[[ 1  0  0  1]
 [ 0  1  1  0]
 [ 1  0  0 -1]
 [ 0  1 -1  0]]


In [23]:
[1, 0, 0, 0]*res

matrix([[1, 0, 0, 1]])

In [24]:
[0, 1, 0, 0]*res

matrix([[0, 1, 1, 0]])

In [25]:
[0, 0, 1, 0]*res

matrix([[ 1,  0,  0, -1]])

In [26]:
[0, 0, 0, 1]*res

matrix([[ 0,  1, -1,  0]])