In [19]:
import numpy as np
qubit = np.array([1 / np.sqrt(2) + 0j, 1 / np.sqrt(2) + 0j]).reshape((2, 1))

In [20]:
print(qubit)

[[0.70710678+0.j]
 [0.70710678+0.j]]


In [21]:
c0 = c1 = 1 / np.sqrt(2) + 0j
p0 = np.conj(c0) * c0
p1 = np.conj(c1) * c1

In [22]:
I = np.matrix([
                [1, 0],
                [0, 1]
])

RN = np.matrix([
                [1+1j, 1-1j],
                [1-1j, 1+1j]
])
CNOT = np.matrix([
                [1, 0, 0, 0],
                [0, 1, 0, 0],
                [0, 0, 0, 1],
                [0, 0, 1, 0]
])
print(I)
print(RN)
print(CNOT)

[[1 0]
 [0 1]]
[[1.+1.j 1.-1.j]
 [1.-1.j 1.+1.j]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]


In [23]:
I_RN = np.tensordot(I, RN, 0)
I_RN = I_RN.transpose((0,2,1,3)).reshape((4,4))
# print(I_RN)

In [24]:
res = I_RN*CNOT
print(res)

[[1.+1.j 1.-1.j 0.+0.j 0.+0.j]
 [1.-1.j 1.+1.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.-1.j 1.+1.j]
 [0.+0.j 0.+0.j 1.+1.j 1.-1.j]]


In [25]:
I_RN1 = np.tensordot(I, RN, 0)
I_RN1 = I_RN1.transpose((0,2,1,3)).reshape((4,4))
# print(I_RN1)

In [26]:
res1 = CNOT*I_RN1
print(res1)

[[1.+1.j 1.-1.j 0.+0.j 0.+0.j]
 [1.-1.j 1.+1.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.-1.j 1.+1.j]
 [0.+0.j 0.+0.j 1.+1.j 1.-1.j]]


In [27]:
res==res1

matrix([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])