In [45]:
import numpy as np
constant = 1/np.sqrt(2)

H = np.matrix([
                [1, 1],
                [1,-1]
])

CNOT = np.matrix([
                [1, 0, 0, 0],
                [0, 1, 0, 0],
                [0, 0, 0, 1],
                [0, 0, 1, 0]
])

NOT = np.matrix([
                [0, 1],
                [1, 0]
])

I = np.matrix([
                [1, 0],
                [0, 1]
])

In [46]:
gadget1 = np.tensordot(H, I, 0)
gadget1 = gadget1.transpose((0,2,1,3)).reshape((4,4))
print(gadget1)

[[ 1  0  1  0]
 [ 0  1  0  1]
 [ 1  0 -1  0]
 [ 0  1  0 -1]]


In [47]:
gadget12 = gadget1*CNOT
print(gadget12)

[[ 1  0  0  1]
 [ 0  1  1  0]
 [ 1  0  0 -1]
 [ 0  1 -1  0]]


In [48]:
res = gadget12*gadget1
print(res)

[[ 1  1  1 -1]
 [ 1  1 -1  1]
 [ 1 -1  1  1]
 [-1  1  1  1]]


In [49]:
[1,0,0,0]*res

matrix([[ 1,  1,  1, -1]])

In [50]:
res*np.matrix([1,0,0,0]).transpose()

matrix([[ 1],
        [ 1],
        [ 1],
        [-1]])

In [51]:
[1,0,0,0]*gadget1

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0]])

In [52]:
gadget12*np.matrix([1,0,0,0]).transpose()

matrix([[1],
        [0],
        [1],
        [0]])

In [53]:
[1,0,0,0]*gadget12

matrix([[1, 0, 0, 1]])