In [4]:
import numpy as np
constant = 1/np.sqrt(2)

H = np.matrix([
                [1, 1],
                [1,-1]
])

CNOT = np.matrix([
                [1, 0, 0, 0],
                [0, 1, 0, 0],
                [0, 0, 0, 1],
                [0, 0, 1, 0]
])

NOT = np.matrix([
                [0, 1],
                [1, 0]
])

I = np.matrix([
                [1, 0],
                [0, 1]
])

In [5]:
gadget1 = np.tensordot(H, I, 0)
gadget1 = gadget1.transpose((0,2,1,3)).reshape((4,4))
print(gadget1)

[[ 1  0  1  0]
 [ 0  1  0  1]
 [ 1  0 -1  0]
 [ 0  1  0 -1]]


In [6]:
gadget2 = gadget1 * CNOT
print(gadget2)

[[ 1  0  0  1]
 [ 0  1  1  0]
 [ 1  0  0 -1]
 [ 0  1 -1  0]]


In [7]:
[1,0,0,0]*gadget2

matrix([[1, 0, 0, 1]])